import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Providers from "@/components/Provider";


const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    //   >
    //       {children}
    //   </body>
    // </html>

    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <div>
            {children}
          </div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}